- name: postgresqlインストール
  yum: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-devel

- name: DBクラスタ初期化
  command: /etc/init.d/postgresql initdb
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: RedmineからPostgresに接続するための設定を追加
  lineinfile:
    state: present
    dest: /var/lib/pgsql/data/pg_hba.conf
    insertafter: "# Put your actual configuration here"
    line: "{{ item }}"
  with_items:
    - "host    redmine         redmine         127.0.0.1/32            md5"
    - "host    redmine         redmine         ::1/128                 md5"

- name: postgresql起動
  service: name=postgresql state=restarted enabled=yes

- name: postgresqlモジュールインストール
  yum: name=python-psycopg2 state=present

- name: postgresユーザー作成
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ user }}"
    password: "{{ pass }}"
    state: present

- name: Redmine用DB作成
  become: yes
  become_user: postgres
  postgresql_db:
    name: redmine
    encoding: "UTF-8"
    owner: "{{ user }}"
    state: present
    template: template0
    login_user: postgres
    lc_ctype: ja_JP.UTF-8
